version: '3.8'

services:
  algo:
    build:
      dockerfile: ./src/Dockerfile
    ports:
      - "8080:8080"
    command: ["/app/algo"]
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
